// <auto-generated />
using System;
using Kutuphane.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kutuphane.Migrations
{
    [DbContext(typeof(KutuphaneDbContext))]
    [Migration("20250601125252_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Kutuphane.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("Kutuphane.Models.Kitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OduncVerildiMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Yayinevi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Yazar")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Kitaplar");
                });

            modelBuilder.Entity("Kutuphane.Models.KitapOduncİslemleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AlinmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("GercekTeslimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KitapAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OduncKitapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OduncKitapId");

                    b.ToTable("kitapOduncİslemleris");
                });

            modelBuilder.Entity("Kutuphane.Models.OduncKitap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KitapId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OduncAlmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TeslimDurumu")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KitapId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OduncKitaplar");
                });

            modelBuilder.Entity("Kutuphane.Models.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciSoyadi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OkulNumarasi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SinifId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SinifId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("Kutuphane.Models.Sinif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SinifAdi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("Kutuphane.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Kutuphane.Models.Kitap", b =>
                {
                    b.HasOne("Kutuphane.Models.Kategori", "Kategori")
                        .WithMany("Kitaplar")
                        .HasForeignKey("KategoriId");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Kutuphane.Models.KitapOduncİslemleri", b =>
                {
                    b.HasOne("Kutuphane.Models.OduncKitap", "OduncKitap")
                        .WithMany()
                        .HasForeignKey("OduncKitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OduncKitap");
                });

            modelBuilder.Entity("Kutuphane.Models.OduncKitap", b =>
                {
                    b.HasOne("Kutuphane.Models.Kitap", "Kitap")
                        .WithMany("OduncKitaplar")
                        .HasForeignKey("KitapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kutuphane.Models.Ogrenci", "Ogrenci")
                        .WithMany("OduncKitaplar")
                        .HasForeignKey("OgrenciId");

                    b.Navigation("Kitap");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("Kutuphane.Models.Ogrenci", b =>
                {
                    b.HasOne("Kutuphane.Models.Sinif", "Sinif")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("SinifId");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("Kutuphane.Models.Kategori", b =>
                {
                    b.Navigation("Kitaplar");
                });

            modelBuilder.Entity("Kutuphane.Models.Kitap", b =>
                {
                    b.Navigation("OduncKitaplar");
                });

            modelBuilder.Entity("Kutuphane.Models.Ogrenci", b =>
                {
                    b.Navigation("OduncKitaplar");
                });

            modelBuilder.Entity("Kutuphane.Models.Sinif", b =>
                {
                    b.Navigation("Ogrenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
